-- MySQL Script generated by MySQL Workbench
-- Fri Jul 17 12:42:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cbpc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cbpc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cbpc` DEFAULT CHARACTER SET utf8 ;
USE `cbpc` ;

-- -----------------------------------------------------
-- Table `cbpc`.`Permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Permissao` (
  `idPermissao` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idPermissao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `idPermissao` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Permissao_idx` (`idPermissao` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Permissao`
    FOREIGN KEY (`idPermissao`)
    REFERENCES `cbpc`.`Permissao` (`idPermissao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Papel` (
  `idPapel` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idPapel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Time` (
  `idTime` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Data_Fundacao` DATE NULL,
  `Sigla` VARCHAR(45) NULL,
  `Criador` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Emblema` VARCHAR(45) NULL,
  `Plataforma` VARCHAR(45) NULL,
  `Jogos` INT NULL,
  `Vitorias` INT NULL,
  `Derrotas` INT NULL,
  `Empates` INT NULL,
  `Titulos` INT NULL,
  `Vice` INT NULL,
  `Terceiro` INT NULL,
  `Gols` INT NULL,
  `Gols_Sofridos` INT NULL,
  PRIMARY KEY (`idTime`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Jogador` (
  `idJogador` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Gamertag` VARCHAR(45) NULL,
  `Plataforma` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Foto_perfil` VARCHAR(100) NULL,
  `Jogos` INT NULL,
  `Vitorias` INT NULL,
  `Derrotas` INT NULL,
  `Empates` INT NULL,
  `Gols` INT NULL,
  `Assistencias` INT NULL,
  `Divididas` INT NULL,
  `Defesas` INT NULL,
  `idUsuario` INT NOT NULL,
  `Titulos` INT NULL,
  `Vices` INT NULL,
  `Terceiro` INT NULL,
  `Estado` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Valor` DOUBLE NULL,
  PRIMARY KEY (`idJogador`),
  INDEX `fk_Jogador_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Jogador_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cbpc`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Papel_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Papel_time` (
  `idTime` INT NOT NULL,
  `idPapel` INT NOT NULL,
  `idJogador` INT NOT NULL,
  `Data_entrada` DATE NULL,
  `Data_saida` DATE NULL,
  INDEX `fk_Papel_time_Time1_idx` (`idTime` ASC) VISIBLE,
  INDEX `fk_Papel_time_Papel1_idx` (`idPapel` ASC) VISIBLE,
  INDEX `fk_Papel_time_Jogador1_idx` (`idJogador` ASC) VISIBLE,
  CONSTRAINT `fk_Papel_time_Time1`
    FOREIGN KEY (`idTime`)
    REFERENCES `cbpc`.`Time` (`idTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Papel_time_Papel1`
    FOREIGN KEY (`idPapel`)
    REFERENCES `cbpc`.`Papel` (`idPapel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Papel_time_Jogador1`
    FOREIGN KEY (`idJogador`)
    REFERENCES `cbpc`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Formato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Formato` (
  `idFormato` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(200) NULL,
  `Regras_padroes` VARCHAR(500) NULL,
  PRIMARY KEY (`idFormato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Campeonato` (
  `idCampeonato` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Regras` VARCHAR(500) NULL,
  `Data_inicio` DATE NULL,
  `Data_termino` DATE NULL,
  `Vagas` INT NULL,
  `Valor_inscricao` DOUBLE NULL,
  `idFormato` INT NOT NULL,
  `Plataforma` VARCHAR(45) NULL,
  `Transferencias` INT NULL,
  `Inicio_transf` DATETIME NULL,
  `Fim_transf` DATETIME NULL,
  PRIMARY KEY (`idCampeonato`),
  INDEX `fk_Campeonato_Formato1_idx` (`idFormato` ASC) VISIBLE,
  CONSTRAINT `fk_Campeonato_Formato1`
    FOREIGN KEY (`idFormato`)
    REFERENCES `cbpc`.`Formato` (`idFormato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Inscricao_campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Inscricao_campeonato` (
  `idInscricao` INT NOT NULL AUTO_INCREMENT,
  `idTime` INT NOT NULL,
  `idCampeonato` INT NOT NULL,
  PRIMARY KEY (`idInscricao`),
  INDEX `fk_Inscricao_campeonato_Time1_idx` (`idTime` ASC) VISIBLE,
  INDEX `fk_Inscricao_campeonato_Campeonato1_idx` (`idCampeonato` ASC) VISIBLE,
  CONSTRAINT `fk_Inscricao_campeonato_Time1`
    FOREIGN KEY (`idTime`)
    REFERENCES `cbpc`.`Time` (`idTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscricao_campeonato_Campeonato1`
    FOREIGN KEY (`idCampeonato`)
    REFERENCES `cbpc`.`Campeonato` (`idCampeonato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Confrontos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Confrontos` (
  `idConfronto` INT NOT NULL AUTO_INCREMENT,
  `Data_inicial` DATE NULL,
  `Data_final` DATE NULL,
  `Time_casa` INT NOT NULL,
  `Time_fora` INT NOT NULL,
  `Horario` TIME NULL,
  `Gols_casa` INT NULL,
  `Gols_fora` INT NULL,
  PRIMARY KEY (`idConfronto`),
  INDEX `fk_Confrontos_Inscricao_campeonato1_idx` (`Time_casa` ASC) VISIBLE,
  INDEX `fk_Confrontos_Inscricao_campeonato2_idx` (`Time_fora` ASC) VISIBLE,
  CONSTRAINT `fk_Confrontos_Inscricao_campeonato1`
    FOREIGN KEY (`Time_casa`)
    REFERENCES `cbpc`.`Inscricao_campeonato` (`idInscricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Confrontos_Inscricao_campeonato2`
    FOREIGN KEY (`Time_fora`)
    REFERENCES `cbpc`.`Inscricao_campeonato` (`idInscricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Jogador_Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Jogador_Partida` (
  `idJogador` INT NOT NULL,
  `idConfronto` INT NOT NULL,
  `idTime` INT NOT NULL,
  `Gols` INT NULL,
  `Assistencias` INT NULL,
  `Divididas` INT NULL,
  `Defesas` INT NULL,
  `Passes` INT NULL,
  `Divididas_certas` INT NULL,
  `Passes_certos` INT NULL,
  `Finalizadoes` INT NULL,
  `Finalizacoes_certas` INT NULL,
  `Gols_contra` INT NULL,
  `Dribles` INT NULL,
  `Gols_sofridos` INT NULL,
  `Bolas_agarradas` INT NULL,
  `Bolas_espalmadas` INT NULL,
  `Cruzamentos_cortados` INT NULL,
  `Bolas_afastadas` INT NULL,
  `Dribles_importantes` INT NULL,
  `Faltas_sofridas` INT NULL,
  `Interceptacoes` INT NULL,
  `Bloqueios` INT NULL,
  `Impedimento` INT NULL,
  `Posse_ganha` INT NULL,
  `Posse_perdida` INT NULL,
  `Chutoes` INT NULL,
  `Cabeceios_ganhos` INT NULL,
  `Cabeceios_perdidos` INT NULL,
  `MVP` INT NULL,
  `Valor` DOUBLE NULL,
  INDEX `fk_Jogador_Partida_Jogador1_idx` (`idJogador` ASC) VISIBLE,
  INDEX `fk_Jogador_Partida_Confrontos1_idx` (`idConfronto` ASC) VISIBLE,
  INDEX `fk_Jogador_Partida_Time1_idx` (`idTime` ASC) VISIBLE,
  CONSTRAINT `fk_Jogador_Partida_Jogador1`
    FOREIGN KEY (`idJogador`)
    REFERENCES `cbpc`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogador_Partida_Confrontos1`
    FOREIGN KEY (`idConfronto`)
    REFERENCES `cbpc`.`Confrontos` (`idConfronto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogador_Partida_Time1`
    FOREIGN KEY (`idTime`)
    REFERENCES `cbpc`.`Time` (`idTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Posicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Posicoes` (
  `idPosicao` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Sigla` VARCHAR(45) NULL,
  `Setor` VARCHAR(45) NULL,
  PRIMARY KEY (`idPosicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cbpc`.`Posicao_Jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cbpc`.`Posicao_Jogador` (
  `idPosicao` INT NOT NULL,
  `idJogador` INT NOT NULL,
  INDEX `fk_Posicao_Jogador_Posicoes1_idx` (`idPosicao` ASC) VISIBLE,
  INDEX `fk_Posicao_Jogador_Jogador1_idx` (`idJogador` ASC) VISIBLE,
  CONSTRAINT `fk_Posicao_Jogador_Posicoes1`
    FOREIGN KEY (`idPosicao`)
    REFERENCES `cbpc`.`Posicoes` (`idPosicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posicao_Jogador_Jogador1`
    FOREIGN KEY (`idJogador`)
    REFERENCES `cbpc`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
