-- MySQL Script generated by MySQL Workbench
-- Thu Apr 15 20:32:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfis` (
  `idperfis` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descrição` VARCHAR(45) NULL,
  `time_created` DATETIME NULL,
  `time_updated` DATETIME NULL,
  PRIMARY KEY (`idperfis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NULL,
  `senha` VARCHAR(45) NULL,
  `time_created` DATETIME NULL,
  `time_updated` DATETIME NULL,
  `idperfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idperfil`),
  INDEX `fk_usuario_perfis_idx` (`idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_perfis`
    FOREIGN KEY (`idperfil`)
    REFERENCES `mydb`.`perfis` (`idperfis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
